name: CI build pipeline


on:
   push:
      branches: [ main ]
pull_request:
   branches: [ main ]


jobs:
   build:
      runs-on: ubuntu-latest
      strategy:
         matrix:
            java: [ '17' ]
            


      steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java}}
          distribution: 'adopt'
          cache: maven
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew build

   
